---

- name: Ensure Supervisor is installed
  apt:
    pkg: supervisor
    state: present
  become: yes
  when: lounge_init_system == "supervisord"

- name: Ensure script to install NodeSource Node.js 4.x repo has been executed
  shell:
    curl -sL https://deb.nodesource.com/setup_4.x | sudo bash -
    creates=/etc/apt/sources.list.d/nodesource.list
  become: yes

- name: Ensure that the latest version of Node.js 4.x (LTS) is installed
  apt:
    pkg: nodejs
    state: latest
  become: yes

- name: Ensure thelounge package is installed
  npm:
    name: thelounge
    global: yes
    production: yes
    version: "{{ lounge_version }}"
    state: present
  become: yes
  notify:
    - Restart lounge
    - Clean up npm temporary files

- name: Ensure user lounge is present
  user:
    name: lounge
    createhome: no
    comment: The Lounge IRC
    system: yes
    state: present
  become: yes

- name: Ensure JS and JSON syntax checking packages are installed
  npm:
    name: "{{ item }}"
    global: yes
    production: yes
    state: present
  with_items:
    - esprima
    - jsonlint
  become: yes

- name: Ensure lounge configuration directory is present
  file:
    path: /etc/lounge
    state: directory
  become: yes

- name: Ensure The Lounge is configured
  template:
    src: config.js.j2
    dest: /etc/lounge/config.js
    validate: 'esvalidate %s'
  become: yes
  notify: Restart lounge

- name: Ensure user configuration directory is present
  file:
    path: /etc/lounge/users
    state: directory
  become: yes
  notify: Restart lounge

- name: Ensure preview storage directory is present
  file:
    path: /etc/lounge/storage
    owner: lounge
    group: lounge
    mode: "0770"
    state: directory
  become: yes
  notify: Restart lounge

- name: Ensure user configuration files are present
  template:
    src: user.json.j2
    dest: /etc/lounge/users/{{ item.user }}.json
    owner: lounge
    group: lounge
    mode: "0660"
    force: no # Do not overwrite existing users to not erase networks
    validate: 'jsonlint -q %s'
  with_items: "{{ lounge_users }}"
  become: yes
  notify: Restart lounge

- name: Ensure program configuration for supervisord is installed
  copy:
    src: lounge_supervisord.conf
    dest: /etc/supervisor/conf.d/lounge.conf
  become: yes
  notify: Restart lounge
  when: lounge_init_system == "supervisord"

- name: Ensure lounge supervisord program is present
  supervisorctl:
    name: lounge
    state: present
  become: yes
  notify: Restart lounge
  when: lounge_init_system == "supervisord"

- name: Ensure systemd unit file is present
  copy:
    dest: /etc/systemd/system/lounge.service
    src: lounge_systemd.service
  become: yes
  notify: Restart lounge
  when: lounge_init_system == "systemd"

- name: Ensure systemd service is started
  service:
    name: lounge
    state: started
    enabled: yes
  become: yes
  when: lounge_init_system == "systemd"
